### ISSUE TITLE
[Bug] Including <std/mem.pat> makes pattern not work.

### ISSUE THREAD

**Issue by pjalsGit** [WerWolv/PatternLanguage#2]
### Operating System

Linux

### What's the issue you encountered?

_(hi, it's the guy with the weird system again!)_

When I add `#include <std/mem.pat>` to the beginning of my pattern, it doesn't show any result in the Pattern Data section, however, if I remove it, it shows the result perfectly.

### How can the issue be reproduced?

- Add this code to the pattern editor (example):
```
#include <std/mem.pat>

bitfield bit { state: 1; };

struct Block {
	char magic[4];
	bit someBits[16];
	char data[4];
};

Block block @ 0x00;
```
- Try to run it, no result
- Remove/comment out `#include <std/mem.pat>`
- Result appears in Pattern Data section

### ImHex Version

01adc8a

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

- `uname -a`: `Linux fedora 5.18.6-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 22 13:46:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- I'm pretty sure it would work on any file but here is the file I was editing when it happened: [miidata02](http://marcansoft.com/transf/miidata02)
- I'm using the AppImage version of ImHex which is known to have some issues.
- This issue is copied from the ImHex repo.

**Comment by WerWolv** [comment]
Hey, is it possible that you still have some old pattern language standard library files installed? I remember fixing something with the mem library.

Try downloading them again from the Content Store

**Comment by WerWolv** [comment]
Also the AppImage shouldn't cause any issues anymore now

**Comment by pjalsGit** [comment]
(I did a clean install of Fedora so I don't think any old ImHex files spilled out)
I have the latest standard library and trying to redownload/reinstall it didn't fix anything unfortunately :(

**Comment by pjalsGit** [comment]
Also, I noticed that it isn't just not showing any results, it simply doesn't want to execute. I tried to put some invalid syntax (putting `aaaaaa` in the middle of the file) and it didn't tell me anything about a syntax error.

**Comment by WerWolv** [comment]
I can reproduce it but only on Linux. Interesting.
I'll have to investigate a bit further later

**Comment by WerWolv** [comment]
Haha very funny error.

It was a combination of two errors. The issue was caused by my Tar helper class extracting files downloaded from the content store wrongly. It appended a bunch of zero bytes behind each file to pad them to 1MB (my extraction buffer size). This alone wouldn't have caused this issue though, the real error was then introduced with my file reader class that didn't properly trim excess zero bytes when reading into a string. So there did end up a bunch of null bytes in the pattern language code when including those files.

The layout of the `std::string` in memory looked like this ultimately:
`[Content of std/mem.pat][00 00 00 00 00 ...][Your pattern code]`

It did parse everything until it hit a null byte and then stopped so only the content of std/mem.pat actually got ever parsed.

So, to fix the error for you now, please download the latest nightly of ImHex, then uninstall the Standard Library from the content store and reinstall it again. The issue should be resolved then.
