### ISSUE TITLE
Issue with Non-Type Template Parameters

### ISSUE THREAD

**Issue by wannkunstbeikor** [WerWolv/PatternLanguage#57]
```
struct SerializedArray<T, auto count>
{
    u32 version;
    T values[count] [[inline]];
};

struct SerializedClass<T>
{
    u32 version;
    T class [[inline]];
};


struct Test
{
    u32 var;
};

struct TestList
{
    u32 count;
    SerializedArray<Test, count> items;
};

struct TestMatrix
{
    u32 count;
    SerializedArray<TestList, count> items;
};

SerializedClass<TestMatrix> testMatrix @0;
```

When u have this nested usage of the template struct SerializedArray and have the Non-Type Template Parameter the same name as the variable u pass into it both times it will take the first one. So in this case the length of items in TestList is count of the TestMatrix. Only when renaming the non-type template param or the variable u pass into it changes, then it will have the correct count. Here is a file that you can test the pattern on and play with the names of the different counts to see how it gets fixed
[test.zip](https://github.com/WerWolv/PatternLanguage/files/11562064/test.zip)

**Comment by paxcut** [comment]
I'm not sure if your interpretation of the results is the right one.  When the same variable name is used in different scopes which one ends up binding the result may differ from language to language depending on the order in which the operations are done. 
To see this I constructed a minimal test example
```cpp
#include <std/io.pat>
#include <std/mem.pat>

struct S<T,auto c> {
    std::print("{}", sizeof(T));
};

u8 count = 5;
S<std::mem::Bytes<count>,7> a;
```
The code is straightforward and this is how most programmers that are used to c/c++ will imagine that it works. After the two includes a struct template is defined but nothing is declared so far. Then count is both defined and declared with the value of 5 assigned to it. That is followed by the declaration of a which is an instantiation of the struct template with two template parameters . The second is a non-type  which is never used (provided to avoid a bug) The first one is a type that has size of count bytes. The struct only purpose is to print the size of the type passed as the first template parameter so we expect this to print 5 and indeed it does that.

Guessing the answer sure is reassuring, but did we analyze the code execution correctly? Can we find some other order of evaluation that gives the same result? Sure. For example imagine that when count is declared the value of 5 is not assigned to it yet. Why would that be? Well, in truth there is no real need to assign it at this moment and if it turns out the value is never used we would have wasted cpu cycles for nothing, so we move on. At the next step 7 is still a useless literal , and the other parameter  has a type dependency, but still no actual value is required yet so we keep going. then we get to the print expression and at this point we need to calculate the size of T so we look for the definition of the type and we find we need count so we look for count to find the value 5. Note that the expressions are visited in the opposite order they were visited before but we got the same answer.

If this explanation seems long and boring it is because at this point we havent learned anything about how the programs is actually evaluated. So we introduce more code that forces the issue to make the answer evident. We do this by creating another variable named count but now we place it in the structure definition and assign a different value to it like this
```cpp
#include <std/io.pat>
#include <std/mem.pat>
struct S<T,auto c> {
    u8 count = 2;
    std::print("{}", sizeof(T));
};
u8 count = 5;
S<std::mem::Bytes<count>,7> a;
```
To see which of the two ways the pattern language uses we simply evaluate the pattern and if the value 5 is printed then pl is like c/c++, but if it prints 2 then it is not. Note that I don't treat either one of the outcomes as a bug. I assume in fact that there are no bugs that affect this simple example. 

As you may have guessed the print shows the value of 2 as being printed. If you want to object to this outcome saying that it is  the result of a bug and it is the same as the bug you found and exhibit in your code consider now changing the example to  this
```cpp
#include <std/io.pat>
#include <std/mem.pat>
struct S<T,auto c> {
    u8 count = 2;
    std::print("{}", sizeof(T));
};

S<std::mem::Bytes<count>,7> a;
```
The change is the removal of the original count =5 statement which would create errors in c/c++  but pl has no problem running it to  print 2. You should be convinced now that the second way we interpreted the evaluation was the correct one. It is clear that count needs not be defined until sizeof is evaluated and the count variable that is the closest to the sizeof evaluation is found first and the one chosen. 

In your code the same thing happens when all the variables are named count and the array is finally defined, PL searches backwards from the array definition to find the value of 1. And when it needs the value of count inside the format function it searches backwards to find the value 5. If you rename the variables it then finds the first one with the correct name which explains why that 'seems' to fix the 'bug' but in fact no bug exists.

Sorry about the long explanation. I don't know any other way to try to explain why there isnt a bug and all there is is that ImHex is not like ordinary languages. Similar error was reported in the ImHex main repo and that is where I got this code from. When I find strange behavior in PL  I don't call it a bug right away, Bugs must show logical inconsistencies, not just unexpected behavior. and I see no inconsistencies here. If you are still unconvinced or I wasn't able to explain things properly  I suggest you try to convince yourself using your code that what I am saying is  valid because at this point I have no more arguments left.

**Comment by wannkunstbeikor** [comment]
hmh Im going to close this issue, but I still dont understand why this way is preferred.
